[Host.HybridMessageSerialzier] Resolve HybridMessageSerializer dependencies from IServiceProvider
zarusz/SlimMessageBus pull request #239
Opened 2024-04-04 04:12 UTC by EtherZa

PR to allow for serializers to be added and then resolved by the hybrid message serializer. 

By resolving the specialized serializers from the DI container, registration of those serializers can be performed via their included builders. This will then allow for the expected dependency resolution path to be followed for each of the specialized serializers ie. JsonMessageSerializer can use a supplied JsonSerializerOptions instance or resolve one from the DI container directly

***Caveat:***
The HybridMessageSerializer must be registered last so that it is able to remove previous IMessageSerializer registrations in order to make itself the designated serializer.

```c#
    services
        .AddSlimMessageBus(mbb =>
        {
            mbb
                // add required serializers to the DI container first
                .AddAvroSerializer()
                .AddGoogleProtobufSerializer()
                .AddJsonSerializer()
                
                // Add hybrid serializer last so that it can update DI container and set itself as the default
                .AddHybridSerializer<JsonMessageSerializer>(
                    o => {

                        // Message1, Message2 => AvroSerializer
                        // Message3 => GoogleProtobufMessageSerializer
                        // all other messages by JsonMessageSerializer

                        o.Add<AvroSerializer>(typeof(Message1), typeof(Message2));
                        o.Add<GoogleProtobufMessageSerializer>(typeof(Message3));
                    })
                ...
        } 

```

2024-04-04 04:41 UTC, EtherZa commented
Removed some syntactic sugar that SonarCloud wasn't a fan of.

2024-04-04 20:29 UTC, zarusz commented on src/SlimMessageBus.Host.Serialization.Hybrid/MessageBusBuilderExtensions.cs
> +        internal ConcurrentDictionary<Type, List<Type>> Registrations { get; } = new();
Do we truly need a concurrent dictionary there? 
I can't see where multiple threads would compete for this collection.

2024-04-04 20:34 UTC, zarusz commented on src/SlimMessageBus.Host.Serialization.Hybrid/README.md
> +Message serialization that is based on message type, delegating serialization to the respective serializer.
There is this section, that would need updating:
https://github.com/zarusz/SlimMessageBus/blob/master/docs/serialization.md#hybrid

2024-04-04 20:40 UTC, zarusz commented on src/SlimMessageBus.Host.Serialization.Hybrid/README.md
> +    services
Whenever possible (or feasable) there is this ps1 script under build folder. It allow would process all the files `*.t.md` and produce `*.md` and it looks at code references to bring in from samples or tests - so that we don't have to copy it over.

You use it like this:

`PS D:\dev\mygithub\SlimMessageBus> .\build\md-preprocessor.ps1`

Have a look here for example:
https://github.com/zarusz/SlimMessageBus/blob/f0615306e94f8a69994d5c70f7552d10936bc154/docs/plugin_asyncapi.t.md?plain=1#L28

In general its good to run if you change any *.t.md file (in the future).

2024-04-04 20:42 UTC, zarusz commented on src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/Helpers/SampleMessages.cs
> +﻿namespace SlimMessageBus.Host.Serialization.Hybrid.Test.Helpers
Please use file-scoped namespaces.

2024-04-04 20:42 UTC, zarusz commented on src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/HybridMessageSerializerTests.cs
> +    using System;
... and use implicit usings where possible

2024-04-04 20:48 UTC, zarusz requested changes
@EtherZa  have a look at a few minor things.

I am also wondering if there is a way we could not require hybrid to be configured as the last (while ensuring backward compatibility with the overall serializer configuration experience).

Looks good overall!

2024-04-05 01:02 UTC, EtherZa commented on src/SlimMessageBus.Host.Serialization.Hybrid/MessageBusBuilderExtensions.cs
> +        internal ConcurrentDictionary<Type, List<Type>> Registrations { get; } = new();
Changed to Dictionary<Type, List<Type>>

2024-04-05 01:03 UTC, EtherZa commented on src/SlimMessageBus.Host.Serialization.Hybrid/README.md
> +Message serialization that is based on message type, delegating serialization to the respective serializer.
Refactored doc change to https://github.com/zarusz/SlimMessageBus/blob/master/docs/serialization.md#hybrid and reverted changes to src/SlimMessageBus.Host.Serialization.Hybrid/README.md

2024-04-05 01:07 UTC, EtherZa commented on src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/Helpers/SampleMessages.cs
> +﻿namespace SlimMessageBus.Host.Serialization.Hybrid.Test.Helpers
Done.

2024-04-05 01:07 UTC, EtherZa commented on src/Tests/SlimMessageBus.Host.Serialization.Hybrid.Test/HybridMessageSerializerTests.cs
> +    using System;
Done.

2024-04-05 09:10 UTC, EtherZa commented
> @EtherZa have a look at a few minor things.
> 
> I am also wondering if there is a way we could not require hybrid to be configured as the last (while ensuring backward compatibility with the overall serializer configuration experience).
> 
> Looks good overall!

I have added a potential option that you may prefer in the [issue](https://github.com/zarusz/SlimMessageBus/issues/238#issuecomment-2038622386).

2024-04-08 21:36 UTC, zarusz approved these changes

2024-04-08 21:36 UTC, merged

2024-04-08 21:39 UTC, zarusz commented
@EtherZa  thanks for your contribution looks good!

If you have a moment would be good to tweak these [4 sonar warnings](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=239&id=zarusz_SlimMessageBus&open=AY68Lub4D9NOPeLwKE2Z).
Else I can look at them in a few days. Cheers.

2024-04-09 02:44 UTC, EtherZa commented
> @EtherZa thanks for your contribution looks good!

Fantastic! 

> If you have a moment would be good to tweak these [4 sonar warnings](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=239&id=zarusz_SlimMessageBus&open=AY68Lub4D9NOPeLwKE2Z) (in another PR). Else I can look at them in a few days. Cheers.

#243 fixes the issues.

Thanks for the support/ideas in getting it across the line.